### ISSUE TITLE
`setup.py` doesn’t work with Python 3.9

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/example-haskell-wheel#2]
```
Traceback (most recent call last):
  File "/Users/runner/work/haskell-wheel/haskell-wheel/setup.py", line 6, in <module>
    from setuptools.errors import ExecError, PlatformError
ImportError: cannot import name 'ExecError' from 'setuptools.errors'
```

**Comment by wenkokke** [comment]
Fixed by switching to the `distutils` errors.
